COLUMNS:
  Month: object
  Total_Income: float
  Total_Expense: float
  Num_Transactions: int
  Avg_Expense: float
  Max_Expense: float
  Low_Balance_Freq: int
  Expense_Income_Ratio: float
  Top_Category_Spend: float
  Risk_Label: object
