COLUMNS:
  Month: object
  Total_Income: float
  Total_Expense: float
  Num_Transactions: int
  Avg_Expense: float
  Max_Expense: float
  Low_Balance_Freq: int
  Expense_Income_Ratio: float
  Top_Category_Spend: float
  Risk_Label: object

TRANSACTION_COLUMNS:
  type: object
  mode: object
  amount: float
  currentBalance: float
  transactionTimestamp: object
  valueDate: object
  txnId: object
  narration: object
  reference: float
